### ISSUE TITLE
group write perms not being set correctly, or php-fpm pool owner not being set correctly

### ISSUE THREAD

**Issue by matrix07012** [pixelfed/docs#31]
I'm using ImageMagick and both ImageResize and AvatarOptimize fail for me because they can't write image data to path.

![image](https://user-images.githubusercontent.com/8049717/66203292-47805e00-e6a8-11e9-8b51-c902ae20ff69.png)
![image](https://user-images.githubusercontent.com/8049717/66203322-61ba3c00-e6a8-11e9-83fd-105513245f56.png)
![image](https://user-images.githubusercontent.com/8049717/66203348-71d21b80-e6a8-11e9-8558-0bb18229399b.png)

**Comment by matrix07012** [comment]
I'm gonna do this, it's probably the best option. But I think that for the sake of simplicity, the install guide should just say that you should run Pixelfed either as www-data or http.

**Comment by trwnh** [comment]
The install guide already does so -- running as a separate user is only included as an info-box. :)

**Comment by salvadorpla** [comment]
Installed Pixelfed v0.10.8 two days ago. Still happening this issue of write perms not being set correctly when uploading new image. 
I think this must be solved and documented to avoid new instances troubles.

**Comment by damsponz** [comment]
Hi,

I Installed Pixelfed v0.10.8 and I have the same issue with apache

I set setuid and setgid for the directory storage like this
`sudo find /home/dso/pixelfed/storage -type d -exec sudo chmod 6775 {} \;`

But the avatar file is stored with the wrong rights, 

`dso@server:~/pixelfed/storage/app/public/avatars/000/000/000/133/392/384/0 $ ls -al`
`drwxr-sr-x 2  www-data dso        4096 mars  23 23:55 .`
`drwxr-sr-x 3  www-data dso        4096 mars  23 23:55 ..`
`-rw-r--r-- 1    www-data dso   1223116 mars  23 23:55 GaWjl2VA4EGQoKrxGNm2_avatar.jpeg`

this is also true for the all directories created UUID

`dso@server:~/pixelfed/storage/app/public/avatars/000 $ ls -al`
`drwxr-sr-x 3  www-data dso 4096 mars  23 23:55 .`
`drwsrwsr-x 3 dso            dso 4096 mars  23 23:55 ..`
`drwxr-sr-x 3  www-data dso 4096 mars  23 23:55 000`

I edit the config/filesystems.php to set the correct permission value (cf. laravel doc)

Nothing works.... All avatar files are created with `www-data` as owner and no write rights for the group, if just on of this two elements is correctly set it works but I don't understand why it doesn't happend.

Did you find a work around or a fix to this ?

best, damsponz.

**Comment by trwnh** [comment]
@damsponz you need to have UMask set to 002 instead of 022 from wherever you're running the php-fpm pool. Add `UMask=0002` to your systemd unit file if you have one, or add `umask 002` to your shell's autostart (.bashrc or similar) if you're just running directly via a `pixelfed` user.

To clarify, the easiest setup is as follows:
- app-user = web-user = http (or whatever your distro uses)
- perms = 755 for directories, 644 for files (default)
  - umask = 022 (default)

For isolating the app-user in the name of security:
- app-user = pixelfed (or something separate)
- web-user = http (or whatever your distro uses)
- perms = app-user has rw(x), web-user has r
  - with default 755/644, this means app-user should own files while web-user should serve them
    - the easiest way to do this is to create a php-fpm pool that runs as the app-user, as described in https://github.com/pixelfed/docs/issues/31#issuecomment-541629733 (and add your web-user to the app-user's group)
  - an alternative that is not recommended anymore: set umask to 002 in both your shell and your systemd unit to force 775/664 on all new files, then add app-user to web-group and web-user to app-group

The former is what is (or rather, was) included in the guide. The latter was only included as a tooltip.

**Comment by damsponz** [comment]
@trwnh Thx

With just umask=0002 in my profile config file it doesn't works. In fact, I missed some elements in the doc, because php-fpm is not a prerequisites [here](https://docs.pixelfed.org/installing-pixelfed/prerequisites.html). So, I didn't have installed this before my comment.

Others prerequisites are missing, the php extensions : `php-imagick` and `php-redis`

It works great with php-fpm pool but in this case I think only this line is necessary : 
`usermod -aG redis pixelfed # give app user access to redis for queues`

the two other are useless, no ?
`usermod -aG pixelfed http  # give web user permission to serve pixelfed`
`usermod -aG redis http     # allow web user to proxy php-fpm to redis`

best regard, damsponz.

**Comment by trwnh** [comment]
Will be fixed in next commits -- `umask` is no longer recommended in Arch guide; creating a dedicated PHP-FPM pool will be shown instead. Default installation will continue to recommend having the web-user run both web and app processes.
